### ISSUE TITLE
国庆期间将不会更新

### ISSUE THREAD

**Issue by Wislove** [Wislove/dqzs#14]
活动的处理可能还存在问题，一些活动的数据获取，奖励购买，可能还会存在断连，封禁的可能，将id加入到活动黑名单就好

**Comment by Wislove** [comment]
或者直接将活动开关关闭

**Comment by Wislove** [comment]
遇到活动购买，然后断联的可以把打印活动id，发出来。vip一般不会断联

**Comment by 20f11c** [comment]
佬可以考虑一下砍树控制双属性比例

**Comment by Shaco-Ma** [comment]
建议将cron改成放在前面，我发现我这边不能重启,如下
const command = `pm2 start app.js --cron "0 1 * * *" --name "${processName}" -- ${filePath}`;

**Comment by Wislove** [comment]
> 建议将cron改成放在前面，我发现我这边不能重启,如下 const command = `pm2 start app.js --cron "0 1 * * *" --name "${processName}" -- ${filePath}`;

一般命令参数的位置，不会影响命令的执行，你这是每天凌晨1点定时执行

**Comment by Wislove** [comment]
> 佬可以考虑一下砍树控制双属性比例

暂无思路，有点难搞

**Comment by 20f11c** [comment]
> > > 建议将cron改成放在前面，我发现我这边不能重启,如下 const command = `pm2 start app.js --cron "0 1 * * *" --name "${processName}" -- ${filePath}`;
> > 
> > 一般命令参数的位置，不会影响命令的执行，你这是每天凌晨1点定时执行
> 跟时间无关,是的啊,但是我这边发现执行pm2之后不会出现cron的提示,移到前面才会出现cron的提示

的确 我的也没重启
