### ISSUE TITLE
开启fightValueFirst参数后 属性高于偏移值的条件也会生效

### ISSUE THREAD

**Issue by zeroT6** [Wislove/dqzs#17]
我直接把属性高于偏移值的注释掉了@@@

**Comment by Wislove** [comment]
妖力优先，当前版本还有一些bug，但如果几个分身妖力差不多，问题也不大。装备返回的妖力值，是当前分身装备该装备后的妖力值。如果拿该值跟其他分身妖力对比，还是有一些bug。正常应该属性符合后，如果妖力会提升，要切换分身，然后再处理装备，比对妖力是否提升。但这样砍树效率会降低，但更准确。目前暂时还没时间处理

**Comment by Wislove** [comment]
妖力优先，当前版本还有一些bug，但如果几个分身妖力差不多，问题也不大。装备返回的妖力值，是当前分身装备该装备后的妖力值。如果拿该值跟其他分身妖力对比，还是有一些bug。正常应该属性符合后，如果妖力会提升，要切换分身，然后再处理装备，比对妖力是否提升。但这样砍树效率会降低，但更准确。目前暂时还没时间处理

**Comment by zhouerfu77322** [comment]
妖力提升建议还是排在quality品质的后面，不然一星什么的装备太乱了
