### ISSUE TITLE
四圣只抓到了摇骰子的事件 resp的请求怎么抓啊

### ISSUE THREAD

**Issue by zeroT6** [Wislove/dqzs#19]
四圣
 * 1. 进入地图 {activityId: 10128319}
 * 2. 摇骰子 S_MONOPOLY_ROLL_DICE {activityId: 10128319}

**Comment by Wislove** [comment]
代码里面搜索协议，CityMsgInfo里面会有响应的返回对象，搜索该返回对象的protobuf文件就可以了
