### ISSUE TITLE
每日松鼠礼包广告没有观看呢

### ISSUE THREAD

**Issue by zhouerfu77322** [Wislove/dqzs#24]

**Comment by zhouerfu77322** [comment]
![image](https://github.com/user-attachments/assets/17ed6960-6b53-4cb7-a282-2a8ce910bd25)

**Comment by Wislove** [comment]
数据同步会有问题，server端会同步很多次数据下来，只有最后一次的数据才可信，暂时先不处理，奖励这一块有时间整体重构

**Comment by Wislove** [comment]
一般都是最后一次的判断会有问题
