### ISSUE TITLE
大佬,这个星宿有bug,你那边知道报文怎么调试吗?

### ISSUE THREAD

**Issue by Shaco-Ma** [Wislove/dqzs#3]

**Comment by zeroT6** [comment]
好像是如果打不过去 就会停止继续打 但是不知道lastbossid是怎么获取

**Comment by Shaco-Ma** [comment]
> 感觉是赋值的问题 不通过后自动停止了 改成下面的试试 if (this.rewardState > 5) { //TODO 不知道全部通关是否是6 logger.info(`[星宿试炼] 任务完成,停止循环`) this.clear() return }

感觉不像是这里的问题,不知道是不是协议改了,我看日志是因为发起了挑战,但是SyncStarTrialData没有返回更新bossid

**Comment by zeroT6** [comment]
> > 感觉是赋值的问题 不通过后自动停止了 改成下面的试试 if (this.rewardState > 5) { //TODO 不知道全部通关是否是6 logger.info(`[星宿试炼] 任务完成,停止循环`) this.clear() return }
> 
> 感觉不像是这里的问题,不知道是不是协议改了,我看日志是因为发起了挑战,但是SyncStarTrialData没有返回更新bossid

你可以截图一下 昨晚我调试是可以返回bossid的（除非你没有打过才不会更新

**Comment by Wislove** [comment]
具体是什么bug，之前的没有看过，要debug调试一下才知道

**Comment by Shaco-Ma** [comment]
> > > 感觉是赋值的问题 不通过后自动停止了 改成下面的试试 if (this.rewardState > 5) { //TODO 不知道全部通关是否是6 logger.info(`[星宿试炼] 任务完成,停止循环`) this.clear() return }
> > 
> > 
> > 感觉不像是这里的问题,不知道是不是协议改了,我看日志是因为发起了挑战,但是SyncStarTrialData没有返回更新bossid
> 
> 你可以截图一下 昨晚我调试是可以返回bossid的（除非你没有打过才不会更新

打过,但是每天第一次发起挑战,这个bossid就不返回,没有搞过这个websocket的调试,拿不到报文.....

**Comment by Shaco-Ma** [comment]
> 具体是什么bug，之前的没有看过，要debug调试一下才知道

我同步一下你的commit试一下看看是否返回

**Comment by Shaco-Ma** [comment]
还是不对的,终期原因是SyncStarTrialData没有返回新的bossid

**Comment by Wislove** [comment]
> 还是不对的,终期原因是SyncStarTrialData没有返回新的bossid
这种异步的程序，服务器要是有数据返回就会触发 SyncStarTrialData，触发时间是不一定的，可能挑战刚开始，就先触发了好几遍SyncStarTrialData。但我没有遇到你的bug。

如果有挑战一次，就不继续的话，可能要考虑换模式，不用原来的登录下发的数据同步，而是执行到这个任务的时候，手动请求，进入星宿，然后靠进入星宿返回的数据来同步，初始值

**Comment by zeroT6** [comment]
> > 还是不对的,终期原因是SyncStarTrialData没有返回新的bossid
> > 这种异步的程序，服务器要是有数据返回就会触发 SyncStarTrialData，触发时间是不一定的，可能挑战刚开始，就先触发了好几遍SyncStarTrialData。但我没有遇到你的bug。
> 
> 如果有挑战一次，就不继续的话，可能要考虑换模式，不用原来的登录下发的数据同步，而是执行到这个任务的时候，手动请求，进入星宿，然后靠进入星宿返回的数据来同步，初始值

87行的赋值问题  如果第一次打不过去 就不会重试了  82行也需要调整不知道为什么只挑战10次

**Comment by Wislove** [comment]
之前的代码里面是这样写的，次数小于20了就不挑战了，更改很简单
