### ISSUE TITLE
游戏版本更新后，分身数据获取失败，无法砍树

### ISSUE THREAD

**Issue by jijunhao** [Wislove/dqzs#30]
是协议换了吗，我对这一块不了解

**Comment by 20f11c** [comment]
> 是协议换了吗，我对这一块不了解

游戏更新用不了了怎么办？ 更新 models 目录即可，非常简单，有手就行。
这是原来开发者说的

**Comment by jijunhao** [comment]
> > 是协议换了吗，我对这一块不了解
> 
> 游戏更新用不了了怎么办？ 更新 models 目录即可，非常简单，有手就行。 这是原来开发者说的

寄，models目录在哪里，没看到欸

**Comment by 20f11c** [comment]
> > > 是协议换了吗，我对这一块不了解
> > 
> > 游戏更新用不了了怎么办？ 更新 models 目录即可，非常简单，有手就行。 这是原来开发者说的
> 
> 寄，models目录在哪里，没看到欸

他应该是反编译的APP

**Comment by Wislove** [comment]
models目录就是/config/grpc目录下的核心文件，protobuf的核心

**Comment by jijunhao** [comment]
> models目录就是/config/grpc目录下的核心文件，protobuf的核心

我大概猜到是这个问题，但是不知道怎么弄到最新版本的config

**Comment by zeroT6** [comment]
> models目录就是/config/grpc目录下的核心文件，protobuf的核心

大佬 请教一下 我反编译后解包 没有app.json文件 是我工具问题吗

**Comment by Wislove** [comment]
> > models目录就是/config/grpc目录下的核心文件，protobuf的核心
> 
> 大佬 请教一下 我反编译后解包 没有app.json文件 是我工具问题吗

这个不太清楚，但即使反编译出来，大概也没啥用，反编译小程序跟小程序解锁F12，代码都差不多，还是很难看懂。反编译apk，又设计到kotlin的反编译。proto都是接口请求的，只是接口加了密

**Comment by Wislove** [comment]
> > models目录就是/config/grpc目录下的核心文件，protobuf的核心
> 
> 我大概猜到是这个问题，但是不知道怎么弄到最新版本的config

小程序断点debug

**Comment by zeroT6** [comment]
> oto都是接口请求的

谢谢大佬 我也debug看看~
