### ISSUE TITLE
大佬求指导

### ISSUE THREAD

**Issue by zeroT6** [Wislove/dqzs#5]
我可以抓到请求的一串数字 然后怎么用脚本解析这条字符啊 想抓一下活动

**Comment by Wislove** [comment]
之前有个hook项目，可以解析，我也在研究如何将抓到的包转发。但其实难点是基于protobuf的文件是如何反编译解析出来的

**Comment by zeroT6** [comment]
> 之前有个hook项目，可以解析，我也在研究如何将抓到的包转发。但其实难点是基于protobuf的文件是如何反编译解析出来的

是的 hook项目可以通过fiddler转发出来每一次请求和发送 但是不知道如何解析 如果有思路可以一起发光发热

**Comment by zeroT6** [comment]
进展：可以抓到protoc文件和请求体结构 但是没有抓到接收的事件格式

**Comment by Wislove** [comment]
> 进展：可以抓到protoc文件和请求体结构 但是没有抓到接收的事件格式

怎么抓到的，什么事件格式。整个体系是 ws + protobuf，抓到的protoc就是它的数据结构。请求就是用ws发送protobuf数据，接收也是接收protobuf数据。 方法里面都是json发送，最后在发的时候json转protobuf数据，接收protobuf数据，转成json，然后再传到各个方法里面。整体目前项目体系来说，基本功能都可以算毕业了，就是优化，修复bug，或者小改了

**Comment by Wislove** [comment]
我也抓到了proto文件，但还没有找到哪里获取的DB文件，还要再debug看看。整体来说现目前版本，基本可以算毕业，就是小修改，增加点小功能
